---
- name: Download the Splunk package (Ubuntu)
  get_url:
    url: "{{ splunk_deb }}"
    dest: "/tmp/{{ splunk_forwarder_deb }}"
    checksum: "{{ splunk_deb_checksum }}"
  when: ansible_os_family == "Debian"

- name: Install Splunk (Ubuntu)
  apt:
    deb: "/tmp/{{ splunk_forwarder_deb }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Download the Splunk package (CentOS)
  get_url:
    url: "{{ splunk_rpm }}"
    dest: "/tmp/{{ splunk_forwarder_rpm }}"
    checksum: "{{ splunk_rpm_checksum }}"
  when: ansible_os_family == "RedHat"

- name: Install Splunk (CentOS)
  yum:
    name: "/tmp/{{ splunk_forwarder_rpm }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Copy inputs file
  template:
    src: inputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    backup: yes
  tags: config_copy

- name: Copy outputs file
  template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    backup: yes
  tags: config_copy

- name: "Enable boot"
  shell:
     "/opt/splunkforwarder/bin/splunk disable boot-start"
  register: enablecmd
  tags: enablecmd

- debug: msg="{{enablecmd.stdout}}"

- name: "start"
  shell:
     "/opt/splunkforwarder/bin/splunk start --accept-license "
  register: startcmd
  tags: startcmd

- debug: msg="{{startcmd.stdout}}"