---
- name: Download the Splunk package (Ubuntu)
  get_url:
    url: "{{ splunk_deb }}"
    dest: "/tmp/{{ splunk_forwarder_deb }}"
    checksum: "{{ splunk_deb_checksum }}"
  when: ansible_os_family == "Debian"

- name: Install Splunk (Ubuntu)
  apt:
    deb: "/tmp/{{ splunk_forwarder_deb }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Download the Splunk package (CentOS)
  get_url:
    url: "{{ splunk_rpm }}"
    dest: "/tmp/{{ splunk_forwarder_rpm }}"
    checksum: "{{ splunk_rpm_checksum }}"
  when: ansible_os_family == "RedHat"

- name: Install Splunk (CentOS)
  yum:
    name: "/tmp/{{ splunk_forwarder_rpm }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Create APP dir
  file:
    path: /opt/splunkforwarder/etc/apps/search/local/
    state: directory

- name: Copy inputs file
  template:
    src: inputs.conf.j2
    dest: /opt/splunkforwarder/etc/apps/search/local/inputs.conf
    backup: yes
  tags: config_copy

- name: Copy outputs file
  template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    backup: yes
  tags: config_copy

#Sets the local password
- name: Remove passwd file
  file:
    path: /opt/splunkforwarder/etc/passwd
    state: absent

- name: copy user seed
  template:
    src: user-seed.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
    backup: yes
  tags: config_copy
#Sets the local password

- name: "Enable boot"
  shell:
     "/opt/splunkforwarder/bin/splunk enable boot-start"
  register: enablecmd
  tags: enablecmd

- debug: msg="{{enablecmd.stdout}}"

- name: "start"
  shell:
     "/opt/splunkforwarder/bin/splunk restart --accept-license --no-prompt --answer-yes"
  register: startcmd
  tags: startcmd

- debug: msg="{{startcmd.stdout}}"